config/routes.rb
Rails.application.routes.draw do
  root to: 'glossaries#index'
  resources :glossaries
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/glossary.rb
class Glossary
  include Mongoid::Document
  include Mongoid::Attributes::Dynamic
  include Mongoid::Timestamps

  field :sl_no, type: String
  field :term, type: String
  field :related_term, type: String
  field :definition, type: String
  field :example, type: String
  field :topic, type: String
  field :reference, type: String
  field :remarks, type: String
  field :url, type: String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/glossaries_controller.rb
class GlossariesController < ApplicationController
  before_action :set_glossary, only: [:show, :edit, :update, :destroy]

  # GET /glossaries
  # GET /glossaries.json
  def index
    @glossaries = Glossary.all
  end

  # GET /glossaries/1
  # GET /glossaries/1.json
  def show
  end

  # GET /glossaries/new
  def new
    @glossary = Glossary.new
  end

  # GET /glossaries/1/edit
  def edit
  end

  # POST /glossaries
  # POST /glossaries.json
  def create
    @glossary = Glossary.new(glossary_params)

    respond_to do |format|
      if @glossary.save
        format.html { redirect_to @glossary, notice: 'Glossary was successfully created.' }
        format.json { render :show, status: :created, location: @glossary }
      else
        format.html { render :new }
        format.json { render json: @glossary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /glossaries/1
  # PATCH/PUT /glossaries/1.json
  def update
    respond_to do |format|
      if @glossary.update(glossary_params)
        format.html { redirect_to @glossary, notice: 'Glossary was successfully updated.' }
        format.json { render :show, status: :ok, location: @glossary }
      else
        format.html { render :edit }
        format.json { render json: @glossary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /glossaries/1
  # DELETE /glossaries/1.json
  def destroy
    @glossary.destroy
    respond_to do |format|
      format.html { redirect_to glossaries_url, notice: 'Glossary was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_glossary
      @glossary = Glossary.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def glossary_params
      params.require(:glossary).permit(:sl_no, :term, :definition, :example, :url, :reference, :remarks)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/glossaries_helper.rb
module GlossariesHelper
end

app/views/glossaries/_form.html.haml
= form_for @glossary, html: { class: "form form-horizontal glossary" } do |f|
  .form-group
    = f.label :sl_no, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :sl_no, class: 'form-control', required: true
    = f.error_span(:sl_no)
  .form-group
    = f.label :term, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :term, class: 'form-control', required: true
    = f.error_span(:term)
  .form-group
    = f.label :definition, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :definition, class: 'form-control', required: true
    = f.error_span(:definition)
  .form-group
    = f.label :example, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_area :example, class: 'form-control', rows: 5
    = f.error_span(:example)
  .form-group
    = f.label :url, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :url, class: 'form-control'
    = f.error_span(:url)
  .form-group
    = f.label :reference, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :reference, class: 'form-control'
    = f.error_span(:reference)
  .form-group
    = f.label :remarks, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :remarks, class: 'form-control'
    = f.error_span(:remarks)
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit nil,class: 'btn btn-primary'
      = link_to t('.cancel', :default => t("helpers.links.cancel")), glossaries_path, :class => 'btn btn-default'

app/views/glossaries/edit.html.haml
- model_class = Glossary
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/glossaries/index.html.haml
- model_class = Glossary
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:sl_no)
      %th= model_class.human_attribute_name(:term)
      %th= model_class.human_attribute_name(:definition)
      %th= model_class.human_attribute_name(:example)
      %th= model_class.human_attribute_name(:url)
      %th= model_class.human_attribute_name(:reference)
      %th= model_class.human_attribute_name(:remarks)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @glossaries.each do |glossary|
      %tr
        %td= link_to glossary.id, glossary_path(glossary)
        %td= glossary.sl_no
        %td= glossary.term
        %td= glossary.definition
        %td= glossary.example
        %td= glossary.url
        %td= glossary.reference
        %td= glossary.remarks
        %td=l glossary.created_at
        %td
          = link_to t('.show', :default => t("helpers.links.show")), glossary_path(glossary), :class => 'btn btn-default btn-xs'
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_glossary_path(glossary), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), glossary_path(glossary), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_glossary_path, :class => 'btn btn-primary'

app/views/glossaries/new.html.haml
- model_class = Glossary
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/glossaries/show.html.haml
- model_class = Glossary
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:sl_no) + ':'
  %br
  = @glossary.sl_no
%p
  %strong= model_class.human_attribute_name(:term) + ':'
  %br
  = @glossary.term
%p
  %strong= model_class.human_attribute_name(:definition) + ':'
  %br
  = @glossary.definition
%p
  %strong= model_class.human_attribute_name(:example) + ':'
  %br
  = @glossary.example
%p
  %strong= model_class.human_attribute_name(:url) + ':'
  %br
  = @glossary.url
%p
  %strong= model_class.human_attribute_name(:reference) + ':'
  %br
  = @glossary.reference
%p
  %strong= model_class.human_attribute_name(:remarks) + ':'
  %br
  = @glossary.remarks


= link_to t('.back', :default => t("helpers.links.back")), glossaries_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_glossary_path(@glossary), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), glossary_path(@glossary), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "RaviRanjanData"
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track": true
    = javascript_include_tag "application", "data-turbolinks-track": true
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"


  %body
    .navbar.navbar-default.navbar-static-top
      .container
        %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand(href="#") RaviRanjanData
        .navbar-collapse.collapse.navbar-responsive-collapse
          %ul.nav.navbar-nav
            %li= link_to "Link 1", "/path1"
            %li= link_to "Link 2", "/path2"
            %li= link_to "Link 3", "/path3"
            %li= link_to "Link 3", "/path3"

    .container
      .row
        .col-lg-9
          = bootstrap_flash
          = yield
        .col-lg-3
          .well.sidebar-nav
            %h3 Sidebar
            %ul.nav.nav-list
              %li.nav-header Sidebar
              %li= link_to "Link 1", "/path1"
              %li= link_to "Link 2", "/path2"
              %li= link_to "Link 3", "/path3"
      %footer
        %p &copy; Company 2018